
import React, { useState } from 'react';
import { 
  Activity, Search, Loader2, Globe, TrendingUp, Twitter, Instagram, 
  Facebook, Hash, Zap, Brain, ShieldCheck, Link as LinkIcon, Sparkles, 
  MessageSquare, User, AlertCircle, RefreshCw, BarChart3, Fingerprint,
  Mail, MessageCircle, Printer, FileDown, FileText, Share2, Copy, Check,
  Volume2, Lock, Crown, ArrowRight
} from 'lucide-react';
import { getSocialIntelligenceAudit } from '../services/gemini';
import { GroundingSource } from '../types';
import { EmailIntelModal } from './EmailIntelModal';
import { ScoutingAudioPlayer } from './ScoutingAudioPlayer';
import { IntelligenceReport } from './IntelligenceReport';

interface SocialPulseHubProps {
  isPro: boolean;
  onRequestPro: () => void;
  // Added onVoiceDeepDive to props interface
  onVoiceDeepDive?: (context: string) => void;
}

// Destructured onVoiceDeepDive from props
export const SocialPulseHub: React.FC<SocialPulseHubProps> = ({ isPro, onRequestPro, onVoiceDeepDive }) => {
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [audit, setAudit] = useState<{ 
    text: string, 
    sources: GroundingSource[], 
    buzzScore: number, 
    sentiment: string 
  } | null>(null);
  
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [copiedDoc, setCopiedDoc] = useState(false);
  const [showAudio, setShowAudio] = useState(false);

  const executeSocialAudit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!query.trim()) return;
    
    setLoading(true);
    setAudit(null);
    setShowAudio(false);
    try {
      const result = await getSocialIntelligenceAudit(query);
      setAudit(result);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleSMS = () => {
    if (!audit) return;
    const smsBody = `PortalIntel Social Audit for ${query}: Buzz Score ${audit.buzzScore}/100, Sentiment: ${audit.sentiment}. Full intel at portalintel.ai`;
    window.open(`sms:?body=${encodeURIComponent(smsBody)}`, '_blank');
  };

  const handleGoogleDocExport = () => {
    if (!audit) return;
    const content = `SOCIAL INTELLIGENCE AUDIT: ${query.toUpperCase()}\nBuzz Score: ${audit.buzzScore}/100\nSentiment: ${audit.sentiment}\n\n${audit.text}\n\nSources:\n${audit.sources.map(s => `- ${s.title}: ${s.uri}`).join('\n')}\n\nGenerated by PortalIntel AI © 2026`;
    navigator.clipboard.writeText(content);
    setCopiedDoc(true);
    setTimeout(() => setCopiedDoc(false), 3000);
    alert("Scouting report copied to clipboard. Paste into your Google Doc or scouting board.");
  };

  const platforms = [
    { name: 'X (Twitter)', icon: Twitter, color: 'text-white' },
    { name: 'Reddit', icon: Hash, color: 'text-orange-500' },
    { name: 'Instagram', icon: Instagram, color: 'text-pink-500' },
    { name: 'Facebook', icon: Facebook, color: 'text-blue-500' },
  ];

  if (!isPro) {
    return (
      <div className="w-full py-12 md:py-20 animate-in fade-in duration-700 px-4 max-w-7xl mx-auto">
        <div className="bg-[#0b1224] border-2 border-dashed border-slate-800 rounded-[2.5rem] md:rounded-[4rem] p-10 md:p-24 flex flex-col items-center text-center relative overflow-hidden">
          <div className="absolute top-0 right-0 w-96 h-96 bg-blue-500/5 rounded-full blur-[100px] -mr-32 -mt-32 pointer-events-none"></div>
          
          <div className="w-20 h-20 md:w-28 md:h-28 bg-slate-900 rounded-[2rem] flex items-center justify-center mb-8 relative shadow-2xl border border-slate-800">
            <Lock className="w-10 h-10 md:w-12 md:h-12 text-slate-700" />
            <div className="absolute -top-2 -right-2">
              <Crown className="w-8 h-8 md:w-10 md:h-10 text-amber-500 animate-pulse" />
            </div>
          </div>
          
          <h2 className="text-3xl md:text-5xl font-black text-white mb-6 tracking-tight uppercase leading-none">Social Hub Locked</h2>
          <p className="text-slate-400 text-base md:text-xl max-w-xl mb-12 leading-relaxed font-medium">
            Neural surveillance of Twitter, Reddit, and IG is reserved for <span className="text-white font-bold">PortalIntel Pro</span> members.
          </p>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full max-w-4xl mb-12">
             <div className="bg-slate-900/40 p-6 rounded-[2rem] border border-slate-800 text-center space-y-3">
                <Activity className="w-6 h-6 text-blue-400 mx-auto" />
                <h4 className="text-xs font-black text-white uppercase tracking-widest">Sentiment Analysis</h4>
                <p className="text-[10px] text-slate-500 font-bold uppercase tracking-tighter">Decode public commitment hints</p>
             </div>
             <div className="bg-slate-900/40 p-6 rounded-[2rem] border border-slate-800 text-center space-y-3">
                <Hash className="w-6 h-6 text-orange-500 mx-auto" />
                <h4 className="text-xs font-black text-white uppercase tracking-widest">Reddit CFB Scans</h4>
                <p className="text-[10px] text-slate-500 font-bold uppercase tracking-tighter">Aggregate community whispers</p>
             </div>
             <div className="bg-slate-900/40 p-6 rounded-[2rem] border border-slate-800 text-center space-y-3">
                <Volume2 className="w-6 h-6 text-purple-400 mx-auto" />
                <h4 className="text-xs font-black text-white uppercase tracking-widest">AI Audio Reports</h4>
                <p className="text-[10px] text-slate-500 font-bold uppercase tracking-tighter">Listen to social intelligence</p>
             </div>
          </div>

          <button 
            onClick={onRequestPro}
            className="group relative bg-blue-600 hover:bg-blue-500 text-white px-12 md:px-16 py-5 md:py-6 rounded-2xl font-black text-sm md:text-base uppercase tracking-widest transition-all shadow-[0_0_40px_rgba(37,99,235,0.3)] active:scale-95 flex items-center justify-center gap-4"
          >
            <ShieldCheck className="w-6 h-6" />
            Initialize Pro Access
            <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full space-y-10 animate-in fade-in duration-700 pb-20 max-w-7xl mx-auto">
      <EmailIntelModal 
        isOpen={showEmailModal} 
        onClose={() => setShowEmailModal(false)} 
        players={[]} 
        reportTitle={`Social Audit: ${query}`}
        initialDraft={audit ? {
          subject: `Scouting Report: Social Intelligence Audit for ${query}`,
          body: `PROSPECT: ${query.toUpperCase()}\nBuzz Score: ${audit.buzzScore}/100\nSentiment: ${audit.sentiment}\n\nINTELLIGENCE SYNTHESIS:\n${audit.text}\n\nVERIFIED SOURCES:\n${audit.sources.map(s => `- ${s.title}: ${s.uri}`).join('\n')}`
        } : undefined}
      />

      <div className="bg-[#0b1224] border border-slate-800 p-8 md:p-12 rounded-[3.5rem] relative overflow-hidden shadow-2xl print:hidden">
         <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-blue-600/5 rounded-full blur-[120px] -mr-64 -mt-64 pointer-events-none"></div>
         
         <div className="relative z-10 flex flex-col md:flex-row items-center justify-between gap-10">
            <div className="space-y-4 text-center md:text-left">
               <div className="flex items-center gap-6">
                  <div className="w-20 h-20 bg-blue-600/10 rounded-3xl flex items-center justify-center border border-blue-500/20 shadow-2xl">
                     <Activity className="w-10 h-10 text-blue-400" />
                  </div>
                  <div>
                     <h2 className="text-4xl md:text-5xl font-black text-white tracking-tighter uppercase leading-none italic">Social Pulse Hub</h2>
                     <div className="flex items-center gap-3 mt-2">
                        <TrendingUp className="w-4 h-4 text-blue-500" />
                        <span className="text-[10px] font-black text-slate-500 uppercase tracking-[0.3em]">Neural Social Grounding: ACTIVE</span>
                     </div>
                  </div>
               </div>
               <p className="text-slate-400 max-w-2xl font-medium leading-relaxed text-lg">
                  Execute deep neural scans across <span className="text-white font-bold">X, Reddit, and IG</span> to uncover commitment hints, character metrics, and real-time portal buzz.
               </p>
            </div>

            <div className="flex items-center gap-4 bg-slate-900/50 border border-slate-800 p-5 rounded-[2rem] shadow-xl">
               {platforms.map((p, i) => (
                 <div key={i} className={`p-3 bg-slate-950 rounded-xl border border-slate-800 shadow-inner group hover:border-blue-500/30 transition-all cursor-pointer`}>
                    <p.icon className={`w-5 h-5 ${p.color} group-hover:scale-110 transition-transform`} />
                 </div>
               ))}
            </div>
         </div>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-[3rem] p-10 shadow-2xl relative overflow-hidden print:hidden">
         <div className="absolute bottom-0 left-0 w-64 h-64 bg-blue-500/5 rounded-full blur-[100px] pointer-events-none"></div>
         
         <form onSubmit={executeSocialAudit} className="relative z-10 space-y-8">
            <div className="space-y-2">
               <label className="text-[10px] font-black text-slate-500 uppercase tracking-[0.4em] ml-4 flex items-center gap-3">
                 <Fingerprint className="w-3 h-3 text-blue-500" /> Initialize Asset Surveillance
               </label>
               <div className="flex bg-slate-950 border border-slate-800 rounded-[1.5rem] overflow-hidden focus-within:ring-2 focus-within:ring-blue-500/30 transition-all shadow-inner">
                  <input 
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                    placeholder="Enter prospect name (e.g. Julian Lewis, Cam Coleman)..."
                    className="flex-1 bg-transparent px-10 py-6 text-white text-xl font-bold placeholder-slate-800 focus:outline-none"
                  />
                  <button 
                    disabled={loading || !query.trim()}
                    className="bg-blue-600 hover:bg-blue-500 disabled:opacity-50 text-white px-12 py-6 font-black uppercase text-sm tracking-widest transition-all active:scale-95 flex items-center gap-3"
                  >
                    {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <Brain className="w-5 h-5" />}
                    Neural Audit
                  </button>
               </div>
            </div>
         </form>
      </div>

      {loading ? (
        <div className="py-32 flex flex-col items-center justify-center text-center gap-10 print:hidden">
           <div className="relative">
              <Loader2 className="w-24 h-24 text-blue-600/20 animate-spin" />
              <Activity className="w-10 h-10 text-blue-500 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 animate-pulse" />
           </div>
           <div className="space-y-4">
              <h3 className="text-3xl font-black text-white uppercase italic tracking-tighter">Crawling Social Nodes...</h3>
              <p className="text-slate-500 font-medium max-w-sm mx-auto uppercase text-[10px] tracking-[0.4em]">Aggregating grounding data from X, Reddit, and CFB Communities</p>
           </div>
        </div>
      ) : audit ? (
        <div className="space-y-10 animate-in fade-in slide-in-from-bottom-6 duration-1000">
           <div className="flex flex-wrap items-center justify-center md:justify-end gap-3 px-2 print:hidden">
              <button onClick={() => setShowAudio(!showAudio)} className={`flex items-center gap-2 px-6 py-3 rounded-xl font-black text-[10px] uppercase tracking-widest shadow-xl transition-all active:scale-95 ${showAudio ? 'bg-purple-600 text-white' : 'bg-purple-900/20 border border-purple-500/20 text-purple-400 hover:bg-purple-600 hover:text-white'}`}><Volume2 className="w-4 h-4" /> {showAudio ? 'Hide Audio' : 'AI Audio Version'}</button>
              <button onClick={() => setShowEmailModal(true)} className="flex items-center gap-2 px-6 py-3 bg-blue-600 hover:bg-blue-500 text-white rounded-xl font-black text-[10px] uppercase tracking-widest shadow-xl transition-all active:scale-95"><Mail className="w-4 h-4" /> Dispatch Email</button>
              <button onClick={handleSMS} className="flex items-center gap-2 px-6 py-3 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl font-black text-[10px] uppercase tracking-widest shadow-xl transition-all active:scale-95"><MessageCircle className="w-4 h-4" /> Send SMS</button>
              <button onClick={handlePrint} className="flex items-center gap-2 px-6 py-3 bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white rounded-xl font-black text-[10px] uppercase tracking-widest shadow-xl transition-all active:scale-95"><Printer className="w-4 h-4" /> Print Report</button>
              <button onClick={handleGoogleDocExport} className="flex items-center gap-2 px-6 py-3 bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white rounded-xl font-black text-[10px] uppercase tracking-widest shadow-xl transition-all active:scale-95">{copiedDoc ? <Check className="w-4 h-4 text-emerald-400" /> : <FileText className="w-4 h-4 text-blue-400" />} {copiedDoc ? 'Copied' : 'Google Doc Prep'}</button>
           </div>

           {showAudio && (
             <div className="max-w-xl ml-auto animate-in slide-in-from-top-4 duration-300 print:hidden">
                <ScoutingAudioPlayer text={`Social Intelligence Report for ${query}. Sentiment is ${audit.sentiment} with a buzz score of ${audit.buzzScore}. ${audit.text}`} label="Social Intel Briefing" onClose={() => setShowAudio(false)} />
             </div>
           )}

           <div className="grid grid-cols-1 lg:grid-cols-12 gap-10">
              <div className="lg:col-span-4 space-y-8">
                 <div className="bg-[#0b1224] border border-slate-800 rounded-[3rem] p-10 shadow-2xl space-y-10 relative overflow-hidden">
                    <div className="absolute top-0 right-0 p-6 opacity-[0.03]"><BarChart3 className="w-32 h-32 text-blue-400" /></div>
                    <div className="text-center space-y-4 relative z-10">
                       <span className="text-[11px] font-black text-blue-500 uppercase tracking-[0.4em]">Sentiment Matrix</span>
                       <div className={`text-5xl font-black uppercase italic tracking-tighter ${audit.sentiment === 'Positive' ? 'text-emerald-400' : audit.sentiment === 'Volatile' ? 'text-rose-400' : 'text-blue-400'}`}>{audit.sentiment}</div>
                    </div>
                    <div className="space-y-4 relative z-10">
                       <div className="flex justify-between items-center px-2"><span className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Neural Buzz Score</span><span className="text-lg font-black text-white">{audit.buzzScore}/100</span></div>
                       <div className="h-2 w-full bg-slate-900 rounded-full overflow-hidden border border-slate-800"><div className="h-full bg-gradient-to-r from-blue-600 to-indigo-500 transition-all duration-[2000ms]" style={{ width: `${audit.buzzScore}%` }}></div></div>
                    </div>
                 </div>
              </div>

              <div className="lg:col-span-8">
                 <div className="bg-[#0b1224] border border-slate-800 rounded-[4rem] p-10 md:p-16 shadow-2xl relative min-h-full">
                    <div className="flex items-center gap-6 mb-12 pb-12 border-b border-slate-800/50">
                       <div className="w-16 h-16 bg-blue-600/10 rounded-[1.75rem] flex items-center justify-center border border-blue-500/20 shadow-inner"><MessageSquare className="w-8 h-8 text-blue-400" /></div>
                       <div>
                          <h3 className="text-2xl md:text-3xl font-black text-white uppercase tracking-tight">Intelligence Synthesis</h3>
                          <p className="text-[10px] font-black text-slate-500 uppercase tracking-[0.3em] mt-1.5">Social Footprint: {query.toUpperCase()}</p>
                       </div>
                    </div>
                    <IntelligenceReport text={audit.text} />
                 </div>
              </div>
           </div>
        </div>
      ) : (
        <div className="py-32 flex flex-col items-center justify-center text-center gap-10 border-2 border-dashed border-slate-800 rounded-[4rem] bg-slate-900/10 opacity-60 group print:hidden">
           <div className="w-24 h-24 rounded-[2rem] bg-slate-800/40 border border-slate-800 flex items-center justify-center shadow-inner group-hover:scale-110 transition-transform"><Activity className="w-10 h-10 text-slate-700" /></div>
           <div className="space-y-3 px-10 max-w-md">
              <h4 className="text-2xl font-black text-slate-400 uppercase tracking-widest">Hub Standby</h4>
              <p className="text-slate-600 text-lg font-medium leading-relaxed italic">Enter a prospect's name above to initialize the <span className="text-blue-500 font-bold">Neural Crawler</span> and audit their social footprint.</p>
           </div>
        </div>
      )}
    </div>
  );
};
